# -*- coding: utf-8 -*-
"""ChatGPT Review Analysis 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OcBj-ojyu2hvWE1T_007ZQRe7ClNvog3
"""

!pip install textblob nltk
import nltk
nltk.download('punkt')
nltk.download('stopwords')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from textblob import TextBlob
from nltk.corpus import stopwords
from collections import Counter

# Replace with your file path
df = pd.read_csv("/content/drive/MyDrive/Crio.do/chatgpt_reviews.csv")

# Standardize column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# Handle missing reviews
df['review'] = df['review'].fillna("")

# Convert date if present
if 'review_date' in df.columns:
    df['review_date'] = pd.to_datetime(df['review_date'], errors='coerce')

# Ensure ratings numeric
if 'ratings' in df.columns:
    df['ratings'] = pd.to_numeric(df['ratings'], errors='coerce')

df.head()

def get_sentiment(text):
    blob = TextBlob(str(text))
    return pd.Series({
        'polarity': blob.sentiment.polarity,      # -1 (neg) → +1 (pos)
    })

df[['polarity']] = df['review'].apply(get_sentiment)
df.head()

# Categorize
def label_sentiment(p):
    if p > 0.1:
        return "Positive"
    elif p < -0.1:
        return "Negative"
    else:
        return "Neutral"

df['sentiment'] = df['polarity'].apply(label_sentiment)

df[['review','ratings','polarity','sentiment']].head()

sns.countplot(data=df, x='sentiment', palette='viridis')
plt.title("Sentiment Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['ratings'], bins=5, kde=False, color="blue")
plt.title("Ratings Distribution")
plt.xlabel("Rating")
plt.ylabel("Count")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['polarity'], bins=30, kde=True, color="green")
plt.title("Polarity Distribution")
plt.show()

# text analysis for words and bigrams extraction
stop_words = set(stopwords.words("english"))

#tokenize text into words and return words if not in stopwords and len>2
def tokenize(text):
    words = re.findall(r'\b\w+\b', text.lower())
    return [w for w in words if w not in stop_words and len(w) > 2]

# Collect tokens
tokens = []
for review in df['review']:
    tokens.extend(tokenize(review))

# Top 20 unigrams using counter
unigram_counts = Counter(tokens).most_common(20)
print(unigram_counts)
uni_df = pd.DataFrame(unigram_counts, columns=["word","count"])

plt.figure(figsize=(10,6))
sns.barplot(data=uni_df, x="count", y="word", palette="mako")
plt.title("Top 20 Frequent Words")
plt.show()

# Bigrams
bigrams = []
for review in df['review']:
    words = tokenize(review)
    for i in range(len(words)-1):
        bigrams.append((words[i], words[i+1]))

bigram_counts = Counter(bigrams).most_common(20)
print(bigram_counts)
bi_df = pd.DataFrame([" ".join(b) for b,c in bigram_counts], columns=["bigram"])
print(bi_df)
bi_df["count"] = [c for b,c in bigram_counts]
print(bi_df)

plt.figure(figsize=(10,6))
sns.barplot(data=bi_df, x="count", y="bigram", palette="viridis")
plt.title("Top 20 Frequent Bigrams")
plt.show()

if 'review_date' in df.columns:
    monthly_reviews = df.groupby(df['review_date'].dt.to_period('M'))['ratings'].count()
    monthly_reviews.plot(kind='line', marker='o', figsize=(10,5))
    plt.title("Monthly Review Volume Trend")
    plt.ylabel("Number of Reviews")
    plt.show()